DROP TABLE IF EXISTS candles_m1;
DROP TABLE IF EXISTS candles_m5;
DROP TABLE IF EXISTS candles_m15;
DROP TABLE IF EXISTS candles_m30;
DROP TABLE IF EXISTS candles_h1;
DROP TABLE IF EXISTS candles_h4;
DROP TABLE IF EXISTS candles_d1;
DROP TABLE IF EXISTS symbols;