CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS symbols (
  name TEXT PRIMARY KEY,
  description TEXT NOT NULL,
  created_time TIMESTAMPTZ DEFAULT NOW(),
  updated_time TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS candles_m1 (
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  FOREIGN KEY (symbol) REFERENCES symbols(name)
);

CREATE TABLE IF NOT EXISTS candles_m5 (
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  FOREIGN KEY (symbol) REFERENCES symbols(name)
);

CREATE TABLE IF NOT EXISTS candles_m15 (
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  FOREIGN KEY (symbol) REFERENCES symbols(name)
);

CREATE TABLE IF NOT EXISTS candles_m30 (
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  FOREIGN KEY (symbol) REFERENCES symbols(name)
);

CREATE TABLE IF NOT EXISTS candles_h1 (
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  FOREIGN KEY (symbol) REFERENCES symbols(name)
);

CREATE TABLE IF NOT EXISTS candles_h4 (
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  FOREIGN KEY (symbol) REFERENCES symbols(name)
);

CREATE TABLE IF NOT EXIStS candles_d1 (
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  FOREIGN KEY (symbol) REFERENCES symbols(name)
);