NAMES = [
    "avg_ema_3_slope_angle",
    "avg_ema_5_slope_angle",
    "rsi_7_slope_angle",
    "rsi_7_sma_slope_angle",
    "rsi_14_slope_angle",
    "rsi_14_sma_slope_angle",
    "macd_6_13_slope_angle",
    "macd_6_13_ema_slope_angle",
    "macd_12_26_slope_angle",
    "macd_12_26_ema_slope_angle",
    "stoch_5_5_k_slope_angle",
    "stoch_5_5_d_slope_angle",
    "stoch_10_10_k_slope_angle",
    "stoch_10_10_d_slope_angle",
    "di_plus_slope_angle",
    "di_minus_slope_angle",
]
